FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build

WORKDIR /source

COPY . ./

RUN dotnet restore ./tests/FakeBitbucketServer/FakeBitbucketServer.csproj

RUN dotnet publish -c Release -o /app ./tests/FakeBitbucketServer/FakeBitbucketServer.csproj

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS runtime

WORKDIR /app

COPY --from=build /app .

ENTRYPOINT ["dotnet", "/app/FakeBitbucketServer.dll"]
