version: 3

tasks: 
  docker-build:
    requires: 
      vars:
        - VERSION
    cmds:
      - docker build --rm -t loremfoobar/sarif-bitbucket-pipe:{{ .VERSION }} .
  docker-build-and-push:
    requires: 
      vars:
        - VERSION
    cmds:
      - task: docker-build
      - docker push loremfoobar/sarif-bitbucket-pipe:{{ .VERSION }}
