<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiffPatch" Version="2.0.0"/>
    <PackageReference Include="Macross.Json.Extensions" Version="3.0.0"/>
    <PackageReference Include="Sarif.Sdk" Version="4.6.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Update="JetBrains.Annotations" Version="2025.2.4" />
  </ItemGroup>

</Project>
