<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LoremFooBar.SarifBitbucketPipe\LoremFooBar.SarifBitbucketPipe.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="JetBrains.Annotations" Version="2025.2.4" />
  </ItemGroup>

</Project>
